**Prerequisites:**
- Collections
- NumPy arrays
- Scalars and vectors
- Bases

### Matrices

So far we have discussed how a basis set of vectors can be used to specify a location of a vector subspace, but how do we describe a vector subspace in linear algebra? The answer is that we use a matrix. A matrix uses the bases set of vectors to define a vector subspace. Let's take the example used in the previous section, where the basis used was

$$ \begin{pmatrix} 2 \\ 0 \\ 0 \end{pmatrix},  \; \begin{pmatrix} 0 \\ 1 \\ 0 \end{pmatrix}, \; \begin{pmatrix} 0 \\ 0 \\ 1 \end{pmatrix} $$

In order to describe a vector subspace using this basis set we arrange our basis such that we create the matrix

$$ \begin{bmatrix}
    2       & 0 & 0 \\
    0       & 1 & 0 \\
    0      & 0 & 1
\end{bmatrix}.
$$

Recall that in order to obtain the point (1,1,1) using this basis set, we used the coordinates (0.5,1,1). These coordinates define a vector using this basis set. In order to get to the point (1,1,1), we must multiple the matrix above by the vector (0.5, 1, 1). We can do this using the "across and down" method. The "across and down" method is illustrated below:

<img src="../images/matrix_multiplication_1.pdf" alt="drawing" width="600"/>

First we define the matrix multiplication we wish to conduct. Then we calculate the first component of our solution by component wise multiplying the first row, with our vector and summing each multiplicative pair (highlighted in red). We then calculate our second component of our solution by the same method (highlighted in purple), and finally we calculate our third component with using the thrid row (highlighted in blue). As we expected we obtain the solution 

$$ \begin{pmatrix} 1 \\ 1 \\ 1 \end{pmatrix}. $$

Let's try something a little more difficult. Imagine we are working in ths subspace defined by the basis set 

$$ \begin{pmatrix} 5 \\ 2 \\ 1 \end{pmatrix},  \; \begin{pmatrix} 1 \\ -1 \\ 1 \end{pmatrix}, \; \begin{pmatrix} 2 \\ -1 \\ 3 \end{pmatrix}.  $$ 

We want to calculate the position given by the vector (2,-1,3) in this subspace. Following the same method as above, we deduce 

<img src="../images/matrix_multiplication_2.pdf" alt="drawing" width="600"/>

How does this work? Let's consider the most general of cases, where our basis set is 

$$ \begin{pmatrix} a_{1} \\ b_{1} \\ c_{1} \end{pmatrix},  \; \begin{pmatrix} a_{2} \\ b_{2} \\ c_{2} \end{pmatrix}, \; \begin{pmatrix} a_{3} \\ b_{3} \\ c_{3} \end{pmatrix},  $$

and the matrix defining our subspace is given by 

$$ \begin{bmatrix}
    a_{1}       & a_{2} & a_{3} \\
    b_{1}       & b_{2} & b_{3} \\
    c_{1}      & c_{2} & c_{3}
\end{bmatrix}.
$$

If we multiply this with the general vector 
$$ \begin{pmatrix} x \\ y \\ z \end{pmatrix}, $$
what do we obtain?

<img src="../images/bases_general.pdf" alt="drawing" width="600"/>

We can see from the above that using matrix multiplication is the same as using the explicit components of the vectors and the basis vectors!

Now that we have a fundamental understanding of what matrices represent, we will discuss how to appropriately depict and use them using the NumPy library. Let's take the simplest 3 $\times$ 3 matrix

$$ \begin{bmatrix}
    1       & 0 & 0 \\
    0       & 1 & 0 \\
    0      & 0 & 1
\end{bmatrix}.
$$

We can represent this in a similar way to the way we represented a vector previously

In [3]:
import numpy as np

matrix = np.array([[1,0,0],
                   [0,1,0],
                   [0,0,1]])


print(matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Note that there are an outer set of square brackets, and inner set of square brackets for each row of the matrix. To compute the product of a matrix and a vector, we use the np.matmul function which stands for matrix multiplication. Let's use python to calculate the second matrix multiplication example above

In [4]:
matrix = np.array([[5,1,2],
                   [2,-1,-1],
                   [1,1,3]])

vector = np.array([2,-1,3])

solution = np.matmul(matrix, vector)
print(solution)

[15  2 10]


The solution returned is as expected from the illustration previously.

**Exercise:** Determine the matrix that describes the vector subspace defined by the following basis set

$$ \begin{pmatrix} 1 \\ 2 \\ 1 \\ 0 \end{pmatrix},  \; \begin{pmatrix} 1 \\ 0 \\ 0 \\ -1 \end{pmatrix}, \; \begin{pmatrix} 2 \\ -2 \\ 1 \\ 0 \end{pmatrix}, \;
\begin{pmatrix} 0 \\ -1 \\ 0 \\ 1 \end{pmatrix}.$$

Calculate the product of the matrix that defines the above vector subspace with the vector 
$$ \begin{pmatrix} 1 \\ -2 \\ 0 \\ 3 \end{pmatrix}. $$

In [5]:
### Write your code here